### ISSUE TITLE
Initial Set-up-2-#13: Add Poem details screen

### ISSUE THREAD

**Issue by gitman876** [gitman876/Poetry#13]
- On click of any poem in the PoemsList screen, user should be directed to the PoemDetails screen (which needs to be implemented in this issue)
- This screen should have the author name, poem title and the lines of the poem.
- `Poem` has this all, it also has `.lineCount`, but unsure how we should use it in the app.
- **WOULD BE BEST TO IMPLEMENT THIS IN SWIFTUI**

**Comment by Azaria92** [comment]
Hello, I would like to attempt this, is it okay?

**Comment by gitman876** [comment]
Completed!

**Comment by gitman876** [comment]
> Hello, I would like to attempt this, is it okay?

Hi, I do apologise, didn't see the comment until now, but this is now completed. Feel free to pick up a new issue
