### ISSUE TITLE
UI- API failure handling

### ISSUE THREAD

**Issue by seymourjr5** [gitman876/Poetry#16]
### Handle UI when API response fails

1. **Add an alert to notify the user that Network Request has been failed.**
- The alert should have two actions, cancel and try again
- Should be implemented for `PoetsList` and `PoemsList` screens

2. **Add a screen to handle Network Response Failure**
- Instead of displaying a blank Table View to the user, show a screen that has the text notifying the user that network request has been failed.
- Should be implemented for both `PoetsList` and `PoemsList` screen

**Comment by gitman876** [comment]
Completed!
