### ISSUE TITLE
Introduce TabBarController

### ISSUE THREAD

**Issue by gitman876** [gitman876/Poetry#24]
- There 

- [x] should be 3 tabs

1. Home
2. Discover
3. Settings 

- [x] `Discover` and `Settings` should be under 'WIP' status 
- [x] `TabBarController` should be hidden for `PoemsLIst` and `PoemDetails` screen
- [x] Home icon for Home tabBar image
- [x] Star for Discover tabBar image
- [x] gearBox for settings tabBar image

**Comment by seymourjr5** [comment]
Completed!!
